package orchestrator

import "testing"

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if cfg.Prism.LogLevel != "info" {
		t.Errorf("expected default log level 'info', got %q", cfg.Prism.LogLevel)
	}
	if cfg.Sessions.IdleTimeoutMinutes != 30 {
		t.Errorf("expected default idle timeout 30, got %d", cfg.Sessions.IdleTimeoutMinutes)
	}
	if cfg.Sessions.DailyResetHour != 4 {
		t.Errorf("expected default daily reset hour 4, got %d", cfg.Sessions.DailyResetHour)
	}
	if cfg.Sessions.MaxContextMessages != 100 {
		t.Errorf("expected default max context 100, got %d", cfg.Sessions.MaxContextMessages)
	}
	if cfg.Sessions.CompactionStrategy != "summarize" {
		t.Errorf("expected default compaction 'summarize', got %q", cfg.Sessions.CompactionStrategy)
	}
	if !cfg.Sessions.Persistence {
		t.Error("expected session persistence enabled by default")
	}
	if !cfg.Sessions.ResumeAfterIdle {
		t.Error("expected resume_after_idle enabled by default")
	}
	if !cfg.Sessions.KeepArchivedMessages {
		t.Error("expected keep_archived_messages enabled by default")
	}
	if cfg.Sessions.ContinuityScope != "owner_agent" {
		t.Errorf("expected continuity_scope owner_agent, got %q", cfg.Sessions.ContinuityScope)
	}
	if cfg.Sessions.RecallWindowMode != "calendar_week" {
		t.Errorf("expected recall_window_mode calendar_week, got %q", cfg.Sessions.RecallWindowMode)
	}
	if cfg.Sessions.RecallTimezone != "Local" {
		t.Errorf("expected recall_timezone Local, got %q", cfg.Sessions.RecallTimezone)
	}
	if cfg.Remembrance.Enabled != false {
		t.Error("expected remembrance disabled by default")
	}
	if cfg.Prism.OllamaURL != "http://localhost:11434" {
		t.Errorf("expected default ollama URL 'http://localhost:11434', got %q", cfg.Prism.OllamaURL)
	}
	if cfg.Prism.LLMTimeoutSeconds != 1200 {
		t.Errorf("expected default LLM timeout 1200, got %d", cfg.Prism.LLMTimeoutSeconds)
	}
	if cfg.Remembrance.TimeoutSeconds != 60 {
		t.Errorf("expected default remembrance timeout 60, got %d", cfg.Remembrance.TimeoutSeconds)
	}
}

func TestValidateEmptyConfig(t *testing.T) {
	cfg := DefaultConfig()
	// Empty config with no agents should be valid
	if err := cfg.Validate(); err != nil {
		t.Errorf("empty config should be valid, got: %v", err)
	}
}

func TestValidateAgentIDs(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid agents should pass: %v", err)
	}
}

func TestValidateAutoGeneratedIDs(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}

	if err := cfg.ResolveAndValidate(); err != nil {
		t.Fatalf("resolve and validate failed: %v", err)
	}
	if cfg.Agents[0].ID != "prism1" {
		t.Errorf("expected first auto-ID 'prism1', got %q", cfg.Agents[0].ID)
	}
	if cfg.Agents[1].ID != "prism2" {
		t.Errorf("expected second auto-ID 'prism2', got %q", cfg.Agents[1].ID)
	}
}

func TestValidateInvalidAgentID(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "bad.id", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for agent ID with dots")
	}
}

func TestValidateDuplicateAgentID(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "lumi", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for duplicate agent ID")
	}
}

func TestValidateMissingRole(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "test", Model: "glm-5.1:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing role")
	}
}

func TestValidateMissingModel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "test", Role: "lead", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing model")
	}
}

func TestValidateChannel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Channels = []ChannelConfig{
		{Type: "discord", Token: "test-token"},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid channel should pass: %v", err)
	}

	// Missing type
	cfg.Channels = []ChannelConfig{{Token: "test"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing channel type")
	}

	// Missing token
	cfg.Channels = []ChannelConfig{{Type: "discord"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing channel token")
	}
}

func TestValidateActions(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Actions = []ActionConfig{
		{Trigger: "*.tool.completed", Action: "prism.cost.track", Enabled: true},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid action should pass: %v", err)
	}

	// Missing trigger
	cfg.Actions = []ActionConfig{{Action: "prism.cost.track"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing trigger")
	}

	// Missing action
	cfg.Actions = []ActionConfig{{Trigger: "*.tool.completed"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing action")
	}
}

func TestValidateSessionConfig(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Sessions.MaxContextMessages = 0
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for max_context_messages < 1")
	}

	cfg.Sessions.MaxContextMessages = 50
	cfg.Sessions.CompactionStrategy = "invalid"
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for invalid compaction_strategy")
	}
}

func TestPrimaryAgent(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama", Primary: true},
	}

	primary := cfg.PrimaryAgent()
	if primary == nil {
		t.Fatal("expected primary agent, got nil")
	}
	if primary.ID != "lumi" {
		t.Errorf("expected primary agent 'lumi', got %q", primary.ID)
	}
}

func TestPrimaryAgentFallback(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "first", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "second", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}

	primary := cfg.PrimaryAgent()
	if primary == nil {
		t.Fatal("expected primary agent fallback, got nil")
	}
	if primary.ID != "first" {
		t.Errorf("expected first agent as fallback, got %q", primary.ID)
	}
}

func TestPrimaryAgentNone(t *testing.T) {
	cfg := DefaultConfig()
	primary := cfg.PrimaryAgent()
	if primary != nil {
		t.Errorf("expected nil for no agents, got %v", primary)
	}
}

func TestValidAgentIDs(t *testing.T) {
	tests := []struct {
		id    string
		valid bool
	}{
		{"lumi", true},
		{"mango", true},
		{"prism1", true},
		{"support-bot", true},
		{"sales-agent", true},
		{"a", true},
		{"abc123", true},
		{"bad.id", false},
		{"bad_id", false},
		{"Bad", false},
		{"", false},
		{"a.b", false},
	}

	for _, tt := range tests {
		got := isValidAgentID(tt.id)
		if got != tt.valid {
			t.Errorf("isValidAgentID(%q) = %v, want %v", tt.id, got, tt.valid)
		}
	}
}
func TestAgentSubscriptions(t *testing.T) {
	cfg := &Config{
		Prism:    PrismConfig{DataDir: "/tmp/prism"},
		Sessions: SessionConfig{MaxContextMessages: 100, IdleTimeoutMinutes: 30, CompactionStrategy: "truncate"},
		Agents: []AgentConfig{
			{
				ID:            "lumi",
				Role:          "lead",
				Provider:      "ollama",
				Model:         "glm-5.1:cloud",
				Primary:       true,
				Subscriptions: []string{"mango.task.completed"},
			},
			{
				ID:            "mango",
				Role:          "coder",
				Provider:      "ollama",
				Model:         "deepseek-v4-pro:cloud",
				Subscriptions: []string{"mango.task.created"},
			},
		},
	}

	if err := cfg.ResolveAndValidate(); err != nil {
		t.Fatalf("unexpected validation error: %v", err)
	}

	if len(cfg.Agents[0].Subscriptions) != 1 {
		t.Errorf("expected 1 subscription for lumi, got %d", len(cfg.Agents[0].Subscriptions))
	}
	if cfg.Agents[0].Subscriptions[0] != "mango.task.completed" {
		t.Errorf("expected mango.task.completed, got %s", cfg.Agents[0].Subscriptions[0])
	}
	if len(cfg.Agents[1].Subscriptions) != 1 {
		t.Errorf("expected 1 subscription for mango, got %d", len(cfg.Agents[1].Subscriptions))
	}
}

func TestAgentSubscriptions_Empty(t *testing.T) {
	cfg := &Config{
		Prism:    PrismConfig{DataDir: "/tmp/prism"},
		Sessions: SessionConfig{MaxContextMessages: 100, IdleTimeoutMinutes: 30, CompactionStrategy: "truncate"},
		Agents: []AgentConfig{
			{ID: "lumi", Role: "lead", Provider: "ollama", Model: "glm-5.1:cloud", Primary: true},
		},
	}

	if err := cfg.ResolveAndValidate(); err != nil {
		t.Fatalf("unexpected validation error: %v", err)
	}

	if len(cfg.Agents[0].Subscriptions) != 0 {
		t.Errorf("expected 0 subscriptions, got %d", len(cfg.Agents[0].Subscriptions))
	}
}

func TestValidateLLMTimeoutNegative(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Prism.LLMTimeoutSeconds = -1
	if err := cfg.Validate(); err == nil {
		t.Error("expected validation error for negative LLM timeout")
	}
}

func TestValidateRemembranceTimeoutNegative(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Remembrance.TimeoutSeconds = -1
	if err := cfg.Validate(); err == nil {
		t.Error("expected validation error for negative remembrance timeout")
	}
}

func TestResolveEnvExpandsChannelToken(t *testing.T) {
	t.Setenv("PRISM_TEST_DISCORD_TOKEN", "test-token")
	cfg, err := LoadConfigFromBytes([]byte(`
agents:
  - id: lumi
    role: lead
    provider: ollama
    model: llama3.2
channels:
  - type: discord
    token: "${PRISM_TEST_DISCORD_TOKEN}"
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.Channels[0].Token != "test-token" {
		t.Fatalf("token = %q", cfg.Channels[0].Token)
	}
}

func TestValidateBridgeRequiresSecret(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Bridge.Enabled = true
	cfg.Bridge.SecretEnv = ""
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected validation error for missing bridge secret")
	}
}

func TestValidateBridgeAllowsInlineSecret(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Bridge.Enabled = true
	cfg.Bridge.SecretEnv = ""
	cfg.Bridge.Secret = "test-secret"
	if err := cfg.Validate(); err != nil {
		t.Fatalf("expected inline bridge secret to validate: %v", err)
	}
}

func TestResolveEnvExpandsBridgeSecret(t *testing.T) {
	t.Setenv("PRISM_TEST_BRIDGE_SECRET", "test-secret")
	cfg, err := LoadConfigFromBytes([]byte(`
bridge:
  enabled: true
  secret_env: ""
  secret: "${PRISM_TEST_BRIDGE_SECRET}"
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.Bridge.Secret != "test-secret" {
		t.Fatalf("bridge secret = %q", cfg.Bridge.Secret)
	}
}

func TestValidateFactoryRunCodexRequiresImplementation(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Bridge.Enabled = true
	cfg.Bridge.SecretEnv = "PRISM_BRIDGE_SECRET"
	cfg.Bridge.Factory.Enabled = true
	cfg.Bridge.Factory.RunCodex = true
	cfg.Bridge.Factory.ApprovalMode = "report_only"
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected validation error for run_codex in report_only mode")
	}
}

func TestValidateBridgeTargetProfiles(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Bridge.Enabled = true
	cfg.Bridge.SecretEnv = ""
	cfg.Bridge.Secret = "test-secret"
	cfg.Bridge.TargetProfiles = []BridgeTargetProfile{
		{Name: "generic", InstanceID: "astraea-manager", Adapter: "generic"},
		{Name: "factory", InstanceID: "astraea-manager", Adapter: "factory"},
	}
	if err := cfg.Validate(); err != nil {
		t.Fatalf("expected target profiles to validate: %v", err)
	}
}

func TestValidateBridgeConfidenceThresholdRange(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Bridge.Enabled = true
	cfg.Bridge.SecretEnv = ""
	cfg.Bridge.Secret = "test-secret"
	cfg.Bridge.ConfidenceThreshold = 1.1
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected validation error for bridge confidence_threshold > 1")
	}
}

func TestValidateCodexDefaultsWhenEnabled(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Prism.Workspace = "D:/workspace"
	cfg.Codex.Enabled = true
	cfg.Codex.Workspace = ""
	cfg.Codex.Sandbox = ""
	cfg.Codex.ApprovalPolicy = ""
	cfg.Codex.TimeoutMinutes = 0
	cfg.Codex.MaxConcurrency = 0
	if err := cfg.Validate(); err != nil {
		t.Fatalf("expected codex config to validate: %v", err)
	}
	if cfg.Codex.Workspace != "D:/workspace" {
		t.Fatalf("workspace = %q", cfg.Codex.Workspace)
	}
	if cfg.Codex.Sandbox != "workspace-write" {
		t.Fatalf("sandbox = %q", cfg.Codex.Sandbox)
	}
	if cfg.Codex.ApprovalPolicy != "on-request" {
		t.Fatalf("approval = %q", cfg.Codex.ApprovalPolicy)
	}
}

func TestValidateCodexRejectsBadApprovalPolicy(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Codex.Enabled = true
	cfg.Codex.Workspace = "."
	cfg.Codex.ApprovalPolicy = "always"
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected validation error for bad codex approval policy")
	}
}

func TestValidateFactoryMonitorDefaultsAndRequiresChannel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.FactoryMonitor.Enabled = true
	cfg.FactoryMonitor.NotifyChannelID = "1496591599940010055"
	cfg.FactoryMonitor.PollSeconds = 0
	cfg.FactoryMonitor.StuckAfterMinutes = 0
	if err := cfg.Validate(); err != nil {
		t.Fatalf("expected factory monitor config to validate: %v", err)
	}
	if cfg.FactoryMonitor.PollSeconds != 30 {
		t.Fatalf("poll_seconds = %d, want 30", cfg.FactoryMonitor.PollSeconds)
	}
	if cfg.FactoryMonitor.StuckAfterMinutes != 30 {
		t.Fatalf("stuck_after_minutes = %d, want 30", cfg.FactoryMonitor.StuckAfterMinutes)
	}

	cfg.FactoryMonitor.NotifyChannelID = ""
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected validation error for missing factory monitor channel")
	}
}

func TestResolveEnvExpandsFactoryMonitorRoot(t *testing.T) {
	t.Setenv("PRISM_TEST_FACTORY_ROOT", "D:/factory")
	cfg, err := LoadConfigFromBytes([]byte(`
factory_monitor:
  enabled: true
  root: "${PRISM_TEST_FACTORY_ROOT}"
  notify_channel_id: "channel"
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if cfg.FactoryMonitor.Root != "D:/factory" {
		t.Fatalf("factory monitor root = %q", cfg.FactoryMonitor.Root)
	}
}

func TestEffectiveRootsPreferSplitConfig(t *testing.T) {
	cfg, err := LoadConfigFromBytes([]byte(`
prism:
  allowed_paths:
    - legacy
  read_roots:
    - reads
  write_roots:
    - writes
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if got := cfg.EffectiveReadRoots(); len(got) != 1 || got[0] != "reads" {
		t.Fatalf("read roots = %v", got)
	}
	if got := cfg.EffectiveWriteRoots(); len(got) != 1 || got[0] != "writes" {
		t.Fatalf("write roots = %v", got)
	}
}

func TestEffectiveRootsFallbackToAllowedPaths(t *testing.T) {
	cfg, err := LoadConfigFromBytes([]byte(`
prism:
  allowed_paths:
    - legacy
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if got := cfg.EffectiveReadRoots(); len(got) != 1 || got[0] != "legacy" {
		t.Fatalf("read roots = %v", got)
	}
	if got := cfg.EffectiveWriteRoots(); len(got) != 1 || got[0] != "legacy" {
		t.Fatalf("write roots = %v", got)
	}
}

func TestResolveOwnerIDUsesAliasesAndDefault(t *testing.T) {
	cfg, err := LoadConfigFromBytes([]byte(`
users:
  - id: ema
    display_name: Ema
    default: true
    aliases:
      discord:
        - "123"
      cli:
        - local-user
`))
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	if got := cfg.ResolveOwnerID("discord", "123"); got != "ema" {
		t.Fatalf("discord alias owner = %q", got)
	}
	if got := cfg.ResolveOwnerID("cli", "local-user"); got != "ema" {
		t.Fatalf("cli alias owner = %q", got)
	}
	if got := cfg.ResolveOwnerID("discord", "unknown"); got != "ema" {
		t.Fatalf("default owner = %q", got)
	}
	aliases := cfg.OwnerAliases("ema")
	if len(aliases) != 3 {
		t.Fatalf("aliases = %v", aliases)
	}
}

func TestValidateSessionRecallConfig(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Sessions.RecallWindowMode = "invalid"
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected invalid recall_window_mode error")
	}

	cfg = DefaultConfig()
	cfg.Sessions.ContinuityScope = "invalid"
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected invalid continuity_scope error")
	}

	cfg = DefaultConfig()
	cfg.Sessions.RecallTimezone = "Not/AZone"
	if err := cfg.Validate(); err == nil {
		t.Fatal("expected invalid recall_timezone error")
	}
}
