package orchestrator

import (
	"testing"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if cfg.Prism.LogLevel != "info" {
		t.Errorf("expected default log level 'info', got %q", cfg.Prism.LogLevel)
	}
	if cfg.Sessions.IdleTimeoutMinutes != 30 {
		t.Errorf("expected default idle timeout 30, got %d", cfg.Sessions.IdleTimeoutMinutes)
	}
	if cfg.Sessions.DailyResetHour != 4 {
		t.Errorf("expected default daily reset hour 4, got %d", cfg.Sessions.DailyResetHour)
	}
	if cfg.Sessions.MaxContextMessages != 100 {
		t.Errorf("expected default max context 100, got %d", cfg.Sessions.MaxContextMessages)
	}
	if cfg.Sessions.CompactionStrategy != "truncate" {
		t.Errorf("expected default compaction 'truncate', got %q", cfg.Sessions.CompactionStrategy)
	}
	if cfg.Remembrance.Enabled != false {
		t.Error("expected remembrance disabled by default")
	}
}

func TestValidateEmptyConfig(t *testing.T) {
	cfg := DefaultConfig()
	// Empty config with no agents should be valid
	if err := cfg.Validate(); err != nil {
		t.Errorf("empty config should be valid, got: %v", err)
	}
}

func TestValidateAgentIDs(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid agents should pass: %v", err)
	}
}

func TestValidateAutoGeneratedIDs(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}

	if err := cfg.ResolveAndValidate(); err != nil {
		t.Fatalf("resolve and validate failed: %v", err)
	}
	if cfg.Agents[0].ID != "prism1" {
		t.Errorf("expected first auto-ID 'prism1', got %q", cfg.Agents[0].ID)
	}
	if cfg.Agents[1].ID != "prism2" {
		t.Errorf("expected second auto-ID 'prism2', got %q", cfg.Agents[1].ID)
	}
}

func TestValidateInvalidAgentID(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "bad.id", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for agent ID with dots")
	}
}

func TestValidateDuplicateAgentID(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "lumi", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for duplicate agent ID")
	}
}

func TestValidateMissingRole(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "test", Model: "glm-5.1:cloud", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing role")
	}
}

func TestValidateMissingModel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "test", Role: "lead", Provider: "ollama"},
	}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing model")
	}
}

func TestValidateChannel(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Channels = []ChannelConfig{
		{Type: "discord", Token: "test-token"},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid channel should pass: %v", err)
	}

	// Missing type
	cfg.Channels = []ChannelConfig{{Token: "test"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing channel type")
	}

	// Missing token
	cfg.Channels = []ChannelConfig{{Type: "discord"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing channel token")
	}
}

func TestValidateActions(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Actions = []ActionConfig{
		{Trigger: "*.tool.completed", Action: "prism.cost.track", Enabled: true},
	}
	if err := cfg.Validate(); err != nil {
		t.Errorf("valid action should pass: %v", err)
	}

	// Missing trigger
	cfg.Actions = []ActionConfig{{Action: "prism.cost.track"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing trigger")
	}

	// Missing action
	cfg.Actions = []ActionConfig{{Trigger: "*.tool.completed"}}
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for missing action")
	}
}

func TestValidateSessionConfig(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Sessions.MaxContextMessages = 0
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for max_context_messages < 1")
	}

	cfg.Sessions.MaxContextMessages = 50
	cfg.Sessions.CompactionStrategy = "invalid"
	if err := cfg.Validate(); err == nil {
		t.Error("expected error for invalid compaction_strategy")
	}
}

func TestPrimaryAgent(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "mango", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
		{ID: "lumi", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama", Primary: true},
	}

	primary := cfg.PrimaryAgent()
	if primary == nil {
		t.Fatal("expected primary agent, got nil")
	}
	if primary.ID != "lumi" {
		t.Errorf("expected primary agent 'lumi', got %q", primary.ID)
	}
}

func TestPrimaryAgentFallback(t *testing.T) {
	cfg := DefaultConfig()
	cfg.Agents = []AgentConfig{
		{ID: "first", Role: "lead", Model: "glm-5.1:cloud", Provider: "ollama"},
		{ID: "second", Role: "coder", Model: "deepseek-v4-pro:cloud", Provider: "ollama"},
	}

	primary := cfg.PrimaryAgent()
	if primary == nil {
		t.Fatal("expected primary agent fallback, got nil")
	}
	if primary.ID != "first" {
		t.Errorf("expected first agent as fallback, got %q", primary.ID)
	}
}

func TestPrimaryAgentNone(t *testing.T) {
	cfg := DefaultConfig()
	primary := cfg.PrimaryAgent()
	if primary != nil {
		t.Errorf("expected nil for no agents, got %v", primary)
	}
}

func TestValidAgentIDs(t *testing.T) {
	tests := []struct {
		id    string
		valid bool
	}{
		{"lumi", true},
		{"mango", true},
		{"prism1", true},
		{"support-bot", true},
		{"sales-agent", true},
		{"a", true},
		{"abc123", true},
		{"bad.id", false},
		{"bad_id", false},
		{"Bad", false},
		{"", false},
		{"a.b", false},
	}

	for _, tt := range tests {
		got := isValidAgentID(tt.id)
		if got != tt.valid {
			t.Errorf("isValidAgentID(%q) = %v, want %v", tt.id, got, tt.valid)
		}
	}
}