# Prism Quality Report Script

$ReportPath = "QUALITY.md"
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

Write-Host "Gathering quality metrics..."

# 1. Go Metrics
$GoPackages = (go list ./... | Measure-Object).Count
$GoTestFiles = (Get-ChildItem -Recurse -Filter "*_test.go" | Measure-Object).Count
$GoTests = (go test -list . ./... | Select-String "^Test" | Measure-Object).Count

# 2. Integration Tests
$IntegrationTests = (go test -list . ./internal/integration | Select-String "^Test" | Measure-Object).Count

# 3. Python Metrics (Remembrance)
$PythonTests = 0
if (Test-Path "remembrance/tests") {
    $PythonTests = (Get-ChildItem -Path "remembrance/tests" -Filter "test_*.py" | Measure-Object).Count
}

# 4. Build Status
$BuildStatus = "Unknown"
go build ./...
if ($LASTEXITCODE -eq 0) { $BuildStatus = "Passing" } else { $BuildStatus = "Failing" }

# 5. Lint Status
$LintStatus = "Unknown"
go vet ./...
if ($LASTEXITCODE -eq 0) { $LintStatus = "Passing" } else { $LintStatus = "Failing" }

# 6. Git Cleanliness
$GitClean = "Clean"
$GitStatus = git status --porcelain
if ($GitStatus) { $GitClean = "Dirty" }

# Generate QUALITY.md
$Content = @"
# Prism Repository Quality Report

Last verified: $Now

## Metrics
- **Go packages:** $GoPackages
- **Go test files:** $GoTestFiles
- **Go tests:** $GoTests
- **Integration tests:** $IntegrationTests
- **Python tests (Remembrance):** $PythonTests
- **Build status:** $BuildStatus
- **Lint status (vet):** $LintStatus
- **Git status:** $GitClean

## Feature Stability Summary
- **Stable:** Workflow Engine, Event Bus, Policy Engine, Approval Gates, Validation Gates, Tool Registry, Providers.
- **Preview:** API, Dashboard, Scheduler, Discord Adapter, Worktree Mutation.
- **Experimental:** Remembrance, MCP, Cross-Prism, Sub-agents, Autopatch.

## CI & Verification
- **Supported Platforms:** Linux, Windows (Basic)
- **Race Testing:** Enabled for core packages (`stage`, `session`, `safety`).
- **Known Limitations:** See [Stability Matrix](./docs/reference/stability-matrix.md).

---
*This report is auto-generated by `scripts/quality-report.ps1`.*
"@

$Content | Out-File -FilePath $ReportPath -Encoding utf8
Write-Host "Quality report generated: $ReportPath"
